#define TK_OP0                             1
#define TK_CAST                            2
#define TK_NEQUAL                          3
#define TK_OP1                             4
#define TK_OP2                             5
#define TK_NOT                             6
#define TK_DOT                             7
#define TK_DCOLON                          8
#define TK_DOT_DOLLAR                      9
#define TK_LSB                            10
#define TK_NL                             11
#define TK_SEMI                           12
#define TK_EOF                            13
#define TK_COMMA                          14
#define TK_CLASS                          15
#define TK_END                            16
#define TK_ID                             17
#define TK_LT                             18
#define TK_DEF                            19
#define TK_LP                             20
#define TK_RP                             21
#define TK_SQUARE                         22
#define TK_NUM                            23
#define TK_NIL                            24
#define TK_TRUE                           25
#define TK_FALSE                          26
#define TK_SELF                           27
#define TK_IVAR                           28
#define TK_LITSTR                         29
#define TK_RSB                            30
#define TK_EQUAL                          31
#define TK_TUPLE_START                    32
#define TK_DICT_START                     33
#define TK_RB                             34
#define TK_LB                             35
#define TK_PIPE                           36
#define TK_IF                             37
#define TK_UNLESS                         38
#define TK_WHILE                          39
#define TK_IMPORT                         40
#define TK_TRY                            41
#define TK_RESCUE                         42
#define TK_OP2_SET                        43
#define TK_OP1_SET                        44
#define TK_OP0_SET                        45
#define TK_RAISE                          46
