#define TK_PLUS                            1
#define TK_MINUS                           2
#define TK_DIVIDE                          3
#define TK_TIMES                           4
#define TK_FIN                             5
#define TK_EOF                             6
#define TK_CLASS                           7
#define TK_END                             8
#define TK_ID                              9
#define TK_DEF                            10
#define TK_COMMA                          11
#define TK_LP                             12
#define TK_RP                             13
#define TK_NUM                            14
#define TK_NIL                            15
#define TK_TRUE                           16
#define TK_FALSE                          17
#define TK_DOT                            18
#define TK_EQUAL                          19
#define TK_CASCADE                        20
#define TK_RB                             21
#define TK_IF                             22
