#define TK_AND                             1
#define TK_OP0                             2
#define TK_LT                              3
#define TK_CAST                            4
#define TK_NEQUAL                          5
#define TK_OP1                             6
#define TK_OP2                             7
#define TK_NOT                             8
#define TK_DOT                             9
#define TK_DCOLON                         10
#define TK_DOT_DOLLAR                     11
#define TK_LSB                            12
#define TK_NL                             13
#define TK_SEMI                           14
#define TK_EOF                            15
#define TK_COMMA                          16
#define TK_CLASS                          17
#define TK_END                            18
#define TK_ID                             19
#define TK_TRAIT                          20
#define TK_DEF                            21
#define TK_LP                             22
#define TK_RP                             23
#define TK_SQUARE                         24
#define TK_NUM                            25
#define TK_NIL                            26
#define TK_TRUE                           27
#define TK_FALSE                          28
#define TK_SELF                           29
#define TK_IVAR                           30
#define TK_LITSTR                         31
#define TK_RSB                            32
#define TK_TUPLE_START                    33
#define TK_DICT_START                     34
#define TK_RB                             35
#define TK_EQUAL                          36
#define TK_LB                             37
#define TK_PIPE                           38
#define TK_IF                             39
#define TK_UNLESS                         40
#define TK_WHILE                          41
#define TK_IMPORT                         42
#define TK_DOT_NAME                       43
#define TK_AS                             44
#define TK_TRY                            45
#define TK_RESCUE                         46
#define TK_OP2_SET                        47
#define TK_OP1_SET                        48
#define TK_OP0_SET                        49
#define TK_RAISE                          50
